name: Build APK and Notify Discord

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set environment variable
      run: |
       echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
       echo "COMMES=$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: gradle

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/debug
        signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Move app
      run: mv app/build/outputs/apk/debug/app-debug-signed.apk app/build/$SHA.apk

    # mv app/build/outputs/apk/release/app-release-unsigned-signed.apk app/build/${SHA}.apk

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
          name: Party
          path: "app/build/$SHA.apk"

    - name: Upload APK to Telegram
      shell: bash
      env:
        BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
        CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${BOT_ID}/sendDocument" \
          -F chat_id="${CHANNEL_ID}" \
          -F document="@app/build/$SHA.apk" \
          -F caption="$COMMES - $SHA"

    - name: Delete Old Pre-Releases
      id: delete-pre-releases
      uses: sgpublic/delete-release-action@master
      with:
        pre-release-drop: true
        pre-release-keep-count: 3
        pre-release-drop-tag: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
